import React, { useEffect, useRef } from 'react';
import { Link } from 'react-router-dom';
import './Landing.css';

const STEPS = [
  {
    num: '01',
    title: 'Set Up Your Company',
    desc: 'Enter your SaaS product details — pricing tiers, features per plan, user counts, and churn rates. Takes less than 5 minutes.',
  },
  {
    num: '02',
    title: 'Add Competitor URLs',
    desc: 'Paste your competitors pricing page URLs. PricePilot automatically scrapes and extracts their pricing data using multi-layer AI scraping.',
  },
  {
    num: '03',
    title: 'AI Runs the Analysis',
    desc: 'Our engine runs 4 modules in parallel — revenue elasticity math, LLM feature classification, competitor benchmarking, and strategy generation.',
  },
  {
    num: '04',
    title: 'Get Actionable Strategies',
    desc: 'Receive a full PDF report with 3 concrete pricing strategies, a revenue chart, competitor positioning, and an AI feature audit.',
  },
];

const FEATURES = [
  {
    title: 'MRR and Price Elasticity Engine',
    desc: 'Simulates 3 pricing scenarios — conservative, moderate, aggressive — showing you exactly what each adjustment does to your Monthly Recurring Revenue.',
    badge: 'Module 1',
  },
  {
    title: 'AI Feature Classifier',
    desc: 'Groq LLM (Llama 3 70B) categorises every feature in your tiers as a value driver, gatekeeper, or blocker so you know exactly what holds upgrades back.',
    badge: 'Module 2',
  },
  {
    title: 'Competitor Benchmarking',
    desc: 'Compares your pricing structure against every competitor you added — positioning, gaps, overlaps, and differentiation opportunities, all generated by AI.',
    badge: 'Module 3',
  },
  {
    title: '3 Tailored Pricing Strategies',
    desc: 'Delivers three fully-fledged pricing strategies with the highest-MRR option clearly marked as Recommended.',
    badge: 'Module 4',
  },
  {
    title: 'Multi-Layer Smart Scraper',
    desc: 'Layer 1 uses HTTP + BeautifulSoup. If that fails, Layer 2 spawns a headless Playwright browser. If that fails, you can enter the data manually.',
    badge: 'Scraper',
  },
  {
    title: 'PDF Report and Email Delivery',
    desc: 'Every analysis auto-generates a beautifully formatted PDF report and emails it directly to you — so your pricing insights are always in your inbox.',
    badge: 'Reports',
  },
];

const STATS = [
  { value: '4', label: 'AI Modules Running in Parallel' },
  { value: '3', label: 'Pricing Strategies Per Analysis' },
  { value: '~2min', label: 'Average Analysis Time' },
  { value: '100%', label: 'Automated — No Manual Work' },
];

export default function Landing() {
  const observerRef = useRef(null);

  useEffect(() => {
    observerRef.current = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) entry.target.classList.add('visible');
        });
      },
      { threshold: 0.12 }
    );
    document.querySelectorAll('.reveal').forEach((el) => observerRef.current.observe(el));
    return () => observerRef.current?.disconnect();
  }, []);

  return (
    <div className="lp-root">
      {/* NAV */}
      <nav className="lp-nav">
        <div className="lp-nav-inner">
          <div className="lp-logo"><span className="lp-logo-icon">✈</span>PricePilot</div>
          <div className="lp-nav-links">
            <Link to="/login" className="lp-btn-ghost">Log in</Link>
            <Link to="/signup" className="lp-btn-primary">Get Started Free</Link>
          </div>
        </div>
      </nav>

      {/* HERO */}
      <section className="lp-hero">
        <div className="lp-hero-bg-orb lp-orb-1" />
        <div className="lp-hero-bg-orb lp-orb-2" />
        <div className="lp-hero-inner">
          <div className="lp-badge">AI-Powered SaaS Pricing Intelligence</div>
          <h1 className="lp-hero-title">
            Stop guessing your pricing.<br />
            <span className="lp-gradient-text">Let AI optimize it.</span>
          </h1>
          <p className="lp-hero-sub">
            PricePilot analyzes your SaaS pricing tiers, scrapes competitor data,
            runs 4 AI modules in parallel, and delivers concrete pricing strategies
            that maximize your MRR — all in under 2 minutes.
          </p>
          <div className="lp-hero-cta">
            <Link to="/signup" className="lp-btn-primary lp-btn-xl">Run Your First Analysis Free</Link>
            <Link to="/login" className="lp-btn-ghost lp-btn-xl">Sign In</Link>
          </div>
          <p className="lp-hero-micro">No credit card required · Free to start · PDF report emailed to you</p>

          {/* Dashboard preview */}
          <div className="lp-preview-card reveal">
            <div className="lp-preview-topbar">
              <div className="lp-preview-dots">
                <span className="dot-r" /><span className="dot-y" /><span className="dot-g" />
              </div>
              <span className="lp-preview-title">PricePilot — Analysis Report</span>
            </div>
            <div className="lp-preview-body">
              <div className="lp-preview-left">
                <div className="lp-preview-label">Recommended MRR Boost</div>
                <div className="lp-preview-big">+$4,230<span className="lp-preview-pct">/ mo</span></div>
                <div className="lp-preview-chip lp-chip-green">34.2% vs current</div>
                <div className="lp-preview-strats">
                  <div className="lp-strat lp-strat-rec">
                    <span className="lp-strat-tag">Recommended</span>
                    <span className="lp-strat-name">Moderate Repositioning</span>
                  </div>
                  <div className="lp-strat"><span className="lp-strat-name">Conservative Tune</span></div>
                  <div className="lp-strat"><span className="lp-strat-name">Aggressive Capture</span></div>
                </div>
              </div>
              <div className="lp-preview-right">
                <div className="lp-preview-label">Revenue Scenarios</div>
                <div className="lp-mini-chart">
                  <div className="lp-mini-bar" style={{height:'52%'}}><span>Current</span></div>
                  <div className="lp-mini-bar lp-bar-mod" style={{height:'78%'}}><span>Moderate</span></div>
                  <div className="lp-mini-bar lp-bar-agg" style={{height:'100%'}}><span>Aggressive</span></div>
                </div>
                <div className="lp-preview-modules">
                  <span className="lp-mod-pill lp-mod-done">Revenue</span>
                  <span className="lp-mod-pill lp-mod-done">Features</span>
                  <span className="lp-mod-pill lp-mod-done">Benchmark</span>
                  <span className="lp-mod-pill lp-mod-done">Strategy</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* STATS */}
      <section className="lp-stats">
        {STATS.map((s) => (
          <div className="lp-stat-item reveal" key={s.label}>
            <div className="lp-stat-value">{s.value}</div>
            <div className="lp-stat-label">{s.label}</div>
          </div>
        ))}
      </section>

      {/* HOW IT WORKS */}
      <section className="lp-section lp-how">
        <div className="lp-section-inner">
          <div className="lp-section-eyebrow reveal">How It Works</div>
          <h2 className="lp-section-title reveal">From setup to strategy in <span className="lp-gradient-text">4 steps</span></h2>
          <p className="lp-section-sub reveal">
            No lengthy onboarding. No consultants. PricePilot handles the heavy lifting — math, scraping, AI, and PDF generation — automatically.
          </p>
          <div className="lp-steps">
            {STEPS.map((step) => (
              <div className="lp-step reveal" key={step.num}>
                <div className="lp-step-num">{step.num}</div>
                <h3 className="lp-step-title">{step.title}</h3>
                <p className="lp-step-desc">{step.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* FEATURES */}
      <section className="lp-section lp-features-section">
        <div className="lp-section-inner">
          <div className="lp-section-eyebrow reveal">Under the Hood</div>
          <h2 className="lp-section-title reveal">6 powerful modules.<br /><span className="lp-gradient-text">One complete analysis.</span></h2>
          <div className="lp-features-grid">
            {FEATURES.map((f) => (
              <div className="lp-feature-card reveal" key={f.title}>
                <div className="lp-feature-top">
                  <span className="lp-feature-badge">{f.badge}</span>
                </div>
                <h3 className="lp-feature-title">{f.title}</h3>
                <p className="lp-feature-desc">{f.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* DELIVERABLE */}
      <section className="lp-section lp-output-section">
        <div className="lp-section-inner lp-output-inner">
          <div className="lp-output-text">
            <div className="lp-section-eyebrow reveal">The Deliverable</div>
            <h2 className="lp-section-title reveal">Every analysis gives you a<br /><span className="lp-gradient-text">complete pricing report</span></h2>
            <ul className="lp-output-list reveal">
              <li><span className="lp-check">✓</span>Executive summary with top recommendation</li>
              <li><span className="lp-check">✓</span>Interactive MRR revenue chart with 3 scenarios</li>
              <li><span className="lp-check">✓</span>Feature-by-feature AI audit table</li>
              <li><span className="lp-check">✓</span>Side-by-side competitor positioning table</li>
              <li><span className="lp-check">✓</span>3 detailed pricing strategy cards</li>
              <li><span className="lp-check">✓</span>Downloadable PDF delivered to your inbox</li>
              <li><span className="lp-check">✓</span>Full history — compare any two past reports</li>
            </ul>
            <Link to="/signup" className="lp-btn-primary lp-btn-xl reveal">Start Your First Analysis</Link>
          </div>
          <div className="lp-output-visual reveal">
            <div className="lp-report-mock">
              <div className="lp-rm-header">
                <div className="lp-rm-logo">✈ PricePilot</div>
                <div className="lp-rm-subtitle">Pricing Analysis Report</div>
              </div>
              <div className="lp-rm-section">
                <div className="lp-rm-label">Executive Summary</div>
                <div className="lp-rm-lines">
                  <div className="lp-rm-line lp-line-long" />
                  <div className="lp-rm-line lp-line-med" />
                  <div className="lp-rm-line lp-line-short" />
                </div>
              </div>
              <div className="lp-rm-section">
                <div className="lp-rm-label">Recommended Strategy</div>
                <div className="lp-rm-strategy-box">
                  <span className="lp-rm-strat-tag">Recommended</span>
                  <div className="lp-rm-line lp-line-med" style={{marginTop:8}} />
                  <div className="lp-rm-line lp-line-long" />
                </div>
              </div>
              <div className="lp-rm-section">
                <div className="lp-rm-label">Competitor Benchmark</div>
                <div className="lp-rm-table">
                  <div className="lp-rm-row lp-rm-thead"><span>Tier</span><span>Your Price</span><span>Avg. Market</span><span>Gap</span></div>
                  <div className="lp-rm-row"><span>Starter</span><span>$29</span><span>$25</span><span className="lp-rm-pos">+16%</span></div>
                  <div className="lp-rm-row"><span>Pro</span><span>$79</span><span>$89</span><span className="lp-rm-neg">-11%</span></div>
                  <div className="lp-rm-row"><span>Enterprise</span><span>$199</span><span>$210</span><span className="lp-rm-neg">-5%</span></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="lp-cta-section">
        <div className="lp-cta-bg-orb" />
        <div className="lp-cta-inner reveal">
          <h2 className="lp-cta-title">
            Ready to find out what your pricing<br />
            <span className="lp-gradient-text">is actually worth?</span>
          </h2>
          <p className="lp-cta-sub">
            Add your company, drop in competitor URLs, and PricePilot does the rest.
            Your first full pricing analysis is completely free.
          </p>
          <div className="lp-cta-btns">
            <Link to="/signup" className="lp-btn-primary lp-btn-xl">Create Free Account</Link>
            <Link to="/login" className="lp-btn-ghost lp-btn-xl">Already have an account</Link>
          </div>
        </div>
      </section>

      {/* FOOTER */}
      <footer className="lp-footer">
        <div className="lp-footer-inner">
          <div className="lp-logo"><span className="lp-logo-icon">✈</span>PricePilot</div>
          <p className="lp-footer-copy">AI-powered pricing analysis for SaaS founders.</p>
          <div className="lp-footer-links">
            <Link to="/login">Log In</Link>
            <Link to="/signup">Sign Up</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
